### PR TITLE
Cherry pick commits from MDL-79113-master_refactor_global_functions branch

### PR DESCRIPTION
**Pull request by alexmorrisnz**
A couple things to note:

- we shouldn't be copying the mod_lti lang file wholesale, I haven't checked if any of the strings from there are being used in the ltixformslib file, I've overwritten the files with the minimum amount of strings required
- lti_submission deals with mod_lti submissions not general LTI submissions, this has been moved back into mod_lti
- ltix_helper is now types_helper
- constants have been removed from `mod/lti/locallib.php` and `ltix_helper`, these are in `ltix/lib.php` tentatively awaiting confirmation on the location

### CODE REVIEW

**Comment by ismael-texidor** [comment]
@alexmorrisnz should this release branch just point to another branch that is not dev-spike to set up a solid foundation for our changes going forward?

**Comment by alexmorrisnz** [comment]
@ismael-texidor That's probably the best way to go, perhaps a new MDL-79109 branch based off of master with these changes to be used as the main branch to be merged into Moodle, and fork off of that for any new features (e.g. LTI asset processor)

**Comment by ismael-texidor** [comment]
@alexmorrisnz Sounds perfect! Please create that new MDL-79109 epic branch and point our changes to it when you have a moment. 

Also update any MDL ticket with the corresponding diff url as the moodle team requested that during our meeting yesterday.

**Comment by alexmorrisnz** [comment]
@ismael-texidor Created https://github.com/turnitin-public/moodle/tree/MDL-79109-master_lti_migration
Haven't put all of the work on it yet, it's missing the unit test changes and the changes from you or @godsonahamba since about the 7th October.

It'd be great if new work can be based off this branch, will help with the moving and cleanup required for making it suitable for Moodle. I'll close this and look into moving the changes you and godson have made since the 7th onto that branch next week, unless someone gets to it before me

I've updated MDL-79113, MDL-79112, MDL-79110 with the git details and they'll be put through CI shortly. I expect there'll be some failures out of this

**Pull request closed without merging**
